version: '3.7'

services:
  front:
    image: "${REPOSITORY_URI}:${TAG}"
    networks:
      - nxsone
    ports:
      - "81:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
networks:
  nxsone:
    driver: overlay
    attachable: true
