version: '3.7'

services:
  front:
    image: "nxs-develop.jelvix.dev/nxs1_frontend:${TAG}"
    networks:
      - nxsone
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
networks:
  nxsone:
    driver: overlay
    attachable: true